### Introduction to NumPy (Numerical Python)
- We can think of all data as arrays of numbers
    - images: 2d array of numbers representing pixel brightness
    - sound clips: 1d arrays of intensity v. time
- The first step to making data "analyzable" is to transform it into arrays of numbers
- NumPy arrays from the core of almost all data science tools in Python


### Understanding Data Types in Python
- How can we store an manipulate data?
- **Note:** in Python, data types are *dynamically inferred*, which is different from Java where you must declare all variable types explicitly
    - Python variables have "type-flexibility", which makes them more than just their value

What is actually happening when I type:


In [1]:
x = 100

- x becomes a pointer to a *compound C structure* with these components
    - ob_refcnt: reference count for handling memory
    - ob_type: encodes type of variable
    - ob_size: size of the data members
    - ob_digit: contains actual integer value the varaible should represent

**Meaning there is a lot of overhead when you just declare an int!**

- A Python integer is more like an object than a primitive type- pointer to position in memory with all object's data
- Consider a list with LOTS of data in it.
    - In Python, the elements don't have to be the same type because each variable keeps track of lots of info to make it dynamic
    - If all of the elements in our list are going to be the same, that's a lot of overhang. We should use something more efficient
        - **NumPy Array** is a fixed type array 

### Fixed-Type Arrays in Python
Creating Arrays from Python Lists

In [4]:
import numpy as np

#create an array
#remember all types within array must be the same
np.array([2,4,6,8])

array([2, 4, 6, 8])

In [5]:
#This should cause an error
np.array(['hi', 4, (8,9)])

ValueError: setting an array element with a sequence

In [7]:
#NumPy will try to cast if possible!
#This should cast the ints to floats
np.array([4.8, 9, 7.2, 3, 5, 6])

array([ 4.8,  9. ,  7.2,  3. ,  5. ,  6. ])

In [19]:
#You can also explicitly choose the data type
#Note: I'm casting floats to ints. They will lose precision
np.array([4.8, 9, 7.2, 3, 5, 6], dtype= 'int')

array([4, 9, 7, 3, 5, 6])