Andrew Ryan

AndrewRyan@pitt.edu

9/7/2017

In [75]:
import numpy as np
print("Numpy version", np.__version__)

Numpy version 1.12.1


In [76]:
np.array([range(i,i * 2) for i in [1, 3, 5]])

array([range(1, 2), range(3, 6), range(5, 10)], dtype=object)

Why does it print out dtype when multiplying? **Above vs Below**

In [77]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [78]:
np.full((4, 3), "cat")

array([['cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat']], 
      dtype='<U3')

In [79]:
np.arange(0, 25, 2.5)

array([  0. ,   2.5,   5. ,   7.5,  10. ,  12.5,  15. ,  17.5,  20. ,  22.5])

In [80]:
np.random.random((4,6))

array([[ 0.21474915,  0.24273964,  0.21810493,  0.16286202,  0.3457213 ,
         0.47832698],
       [ 0.92167936,  0.33203425,  0.33540265,  0.42222733,  0.64296753,
         0.00662729],
       [ 0.65575334,  0.58052785,  0.26206003,  0.26324061,  0.33599413,
         0.00426955],
       [ 0.55360896,  0.04723393,  0.87963018,  0.58130338,  0.16805911,
         0.3683958 ]])

In [81]:
foo = np.random.randint(100, size=(3, 3))
foo

array([[47, 38, 78],
       [65, 84, 28],
       [ 5, 66, 90]])

In [82]:
print("Center number is", foo[1,1])

Center number is 84
