Alan Juffs. juffs@pitt.edu. 09/07/2017. Numpy Notes

These are the numpy notes for 'To Do 2'

Numpy is a program used to perform analysis on data sets, which are more complex than simple lists.
This is done by creating 'arrays' as explained in Data Camp. An example of two lists is in (1), scores on two tests of ESL profiency. Once entered as a list, the list can be called and produced an 'out', confirming the list.

In [3]:
ScoreT1 = [10, 8, 8, 7, 5, 8, 7, 6, 1, 9]
ScoreT2 = [9, 9, 5, 7, 6, 9, 10, 6, 4, 10]
ScoreT1

[10, 8, 8, 7, 5, 8, 7, 6, 1, 9]

These two lists are useful basic lists, but numpy allows us to carry out calculations and to manipulate them. numpy is a function that can be 'called' in Python. Once called, it can be used to carry out manipulations of lists. 

In [4]:
import numpy as np

numpy allows a researcher to combine lists into an 'array' in order to carry out more sophisticated operations on a data set. For example, the Scores for Time 1(T1) and Time 2 (Time2) can be combined and then operations performed on them. If we try and do a statistical operations on two lists, it won't work. For example, we might be interested in correlating T1 and and T2 scores, but this produces an error:

In [5]:
np.corrcoef (ScoreT1) (ScoreT2)

TypeError: 'numpy.float64' object is not callable

Instead, we need to create an 'array' of the two sets of scores. 

In [7]:
np_2d = np.array ([[10, 8, 8, 7, 5, 8, 7, 6, 1, 9], [9, 9, 5, 7, 6, 9, 10, 6, 4, 10]])


Now the data are in one table and can be manipulated: the data can be examined thus:

In [11]:
np_2d

array([[10,  8,  8,  7,  5,  8,  7,  6,  1,  9],
       [ 9,  9,  5,  7,  6,  9, 10,  6,  4, 10]])

In [12]:
np_2d.shape

(2, 10)

These two commands tell us that the data are successfully loaded into an array that has 2 rows and 10 columns. Now we can ask for means of the two sets of scores and standard deviations.

In [15]:
np.mean(np_2d[:,0])

9.5

In [21]:
np.std(np_2d[:,0])

0.5

In [16]:
np.mean(np_2d[0,:])

6.9000000000000004

In [19]:
help(np.corrcoef)

Help on function corrcoef in module numpy.lib.function_base:

corrcoef(x, y=None, rowvar=1, bias=<class 'numpy._globals._NoValue'>, ddof=<class 'numpy._globals._NoValue'>)
    Return Pearson product-moment correlation coefficients.
    
    Please refer to the documentation for `cov` for more detail.  The
    relationship between the correlation coefficient matrix, `R`, and the
    covariance matrix, `C`, is
    
    .. math:: R_{ij} = \frac{ C_{ij} } { \sqrt{ C_{ii} * C_{jj} } }
    
    The values of `R` are between -1 and 1, inclusive.
    
    Parameters
    ----------
    x : array_like
        A 1-D or 2-D array containing multiple variables and observations.
        Each row of `x` represents a variable, and each column a single
        observation of all those variables. Also see `rowvar` below.
    y : array_like, optional
        An additional set of variables and observations. `y` has the same
        shape as `x`.
    rowvar : int, optional
        If `rowvar` is non-zero (

It turns out that a correlation doesn't work well. Instead, it seems the scores have to be in an array that pairs the scores: [10, 9], using the transpose command based on the example in DataCamp.

In [23]:
np_2d.transpose()

array([[10,  9],
       [ 8,  9],
       [ 8,  5],
       [ 7,  7],
       [ 5,  6],
       [ 8,  9],
       [ 7, 10],
       [ 6,  6],
       [ 1,  4],
       [ 9, 10]])

In [24]:
np.corrcoef(np_2d[:,0], np_2d[:,1])

array([[ 1., -1.],
       [-1.,  1.]])

However, this does not produce the correct correlation coefficient. The scores are not perfectly negatively correlated! Frustrating! 

In [26]:
np.mean(np_2d[:,0])

9.5

In [ ]:
np.(np_2d[:,0])

In [27]:
np.mean(np_2d[0,:])

6.9000000000000004