Andrew Ryan

AndrewRyan@pitt.edu

9/7/2017

In [212]:
import numpy as np
print("Numpy version", np.__version__)

Numpy version 1.12.1


In [213]:
np.array([range(i,i * 2) for i in [1, 3, 5]])

array([range(1, 2), range(3, 6), range(5, 10)], dtype=object)

Why does it print out dtype when multiplying? **Above vs Below**

In [214]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [215]:
np.full((4, 3), "cat")

array([['cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat']], 
      dtype='<U3')

In [216]:
np.arange(0, 25, 2.5)

array([  0. ,   2.5,   5. ,   7.5,  10. ,  12.5,  15. ,  17.5,  20. ,  22.5])

In [217]:
np.random.random((4,6))

array([[ 0.26126038,  0.89314367,  0.5763122 ,  0.98630034,  0.2731364 ,
         0.71925123],
       [ 0.80927808,  0.2670973 ,  0.16614438,  0.91580019,  0.06886609,
         0.74904903],
       [ 0.65823386,  0.4590311 ,  0.54632011,  0.2262407 ,  0.92447481,
         0.60273972],
       [ 0.18360908,  0.20549742,  0.86152571,  0.57020481,  0.98892448,
         0.84352777]])

In [218]:
foo = np.random.randint(100, size=(3, 3))
foo

array([[31, 99, 36],
       [41,  7, 55],
       [83, 71, 38]])

In [219]:
print("Center number is", foo[1,1])

Center number is 7


x[start:stop:step]

- If step is negative, list is reversed

In [220]:
foo2  = foo[:2,:2]
foo2

array([[31, 99],
       [41,  7]])

In [221]:
foo[0,0] = 100
foo2

array([[100,  99],
       [ 41,   7]])

In [222]:
foo3 = foo2.copy()
foo3[0,0] = 0
print(foo3,"\n")
print(foo)

[[ 0 99]
 [41  7]] 

[[100  99  36]
 [ 41   7  55]
 [ 83  71  38]]


In [223]:
x = np.arange(1,26).reshape((5,5))
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [224]:
np.concatenate([foo2,foo3])

array([[100,  99],
       [ 41,   7],
       [  0,  99],
       [ 41,   7]])

In [225]:
print(x/5)

[[ 0.2  0.4  0.6  0.8  1. ]
 [ 1.2  1.4  1.6  1.8  2. ]
 [ 2.2  2.4  2.6  2.8  3. ]
 [ 3.2  3.4  3.6  3.8  4. ]
 [ 4.2  4.4  4.6  4.8  5. ]]


In [226]:
print(-x)

[[ -1  -2  -3  -4  -5]
 [ -6  -7  -8  -9 -10]
 [-11 -12 -13 -14 -15]
 [-16 -17 -18 -19 -20]
 [-21 -22 -23 -24 -25]]


In [227]:
print(np.abs(-x))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [228]:
x = [2, 4, 6]
print(np.power(x, 2))

[ 4 16 36]


In [229]:
x = np.arange(1,11)
x = np.multiply.outer(x,x)
print(x)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [230]:
np.sum(x[0])

55

In [231]:
np.max(x[2])

30

**NOTE THE DIFFERENCE**

In [232]:
a = [1,2,3,4,5,6,7,8,9]
b = [9,8,7,6,5,4,3,2,1]
a+b

[1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [233]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([9,8,7,6,5,4,3,2,1])
a+b

array([10, 10, 10, 10, 10, 10, 10, 10, 10])

**WHY DOES THIS HAPPEN**

In [237]:
print(x)
find = [(9,0),(9,1)]
x[find]

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


array([100,   2])