In [58]:
import numpy as np

In [59]:
height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])

In [60]:
np_height = np.array(height)

In [61]:
np_height

array([ 1.73,  1.68,  1.71,  1.89,  1.79])

In [62]:
np_weight = np.array(weight)

In [63]:
np_weight

array([ 65.4,  59.2,  63.6,  88.4,  68.7])

In [64]:
bmi = np_weight / np_height ** 2

In [65]:
bmi

array([ 21.85171573,  20.97505669,  21.75028214,  24.7473475 ,  21.44127836])

Assumes the array only contains one type of value (only floats or booleans, etc.). If it is mixed, NumPy converts everything to strings

In [66]:
python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])

In [67]:
python_list + python_list

[1, 2, 3, 1, 2, 3]

In [68]:
numpy_array + numpy_array

array([2, 4, 6])

Lists will add themselves on top of other lists while NumPy arrays will add their values together.

In [69]:
bmi [1]

20.975056689342409

In [70]:
bmi > 23

array([False, False, False,  True, False], dtype=bool)

In [71]:
bmi[bmi > 23]

array([ 24.7473475])

Using brackets, you can specify which piece of data is printed from the array. Using things like the > or the < will produce an array with boolean values. In this case since only one of the values matched the input, there were 4 False and 1 True. Using brackets again, the array can print the numbers instead of the boolean value by searching the query within the array.

In [72]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],[65.4, 59.2, 63.6, 88.4, 68.7]])
np_2d

array([[  1.73,   1.68,   1.71,   1.89,   1.79],
       [ 65.4 ,  59.2 ,  63.6 ,  88.4 ,  68.7 ]])

In [73]:
np_2d.shape

(2, 5)

In [74]:
np_2d[0][2]

1.71

In [75]:
np_2d[0,2]

1.71

The brackets after np_2d first select the row and then the column and will output the value selected in the multi dimensional array. Either of the formats above can be used.

In [76]:
np_2d[:,1:3]

array([[  1.68,   1.71],
       [ 59.2 ,  63.6 ]])

In [77]:
np_2d[1,:]

array([ 65.4,  59.2,  63.6,  88.4,  68.7])

A ":" can be used to specify all rows or columns and can be used as a means to select only certain rows or columns. The [1:3] selected the second and fourth columns from the array.

In [80]:
np.mean(np_2d[0,:])

1.7600000000000002

In [79]:
np.median(np_2d[0,:])

1.73

In [81]:
np.corrcoef(np_2d[0,:], np_2d[1,:])

array([[ 1.        ,  0.97514969],
       [ 0.97514969,  1.        ]])

In [82]:
np.std(np_2d[0,:])

0.074296702484026825

NumPy functions can be used to check things like the mean and median, as well as other things like checking to see if there is a correlation between the two rows using the np.corrcoef function and checking the standard deviation with np.std. NumPy also includes other things like sum() and sort() that are faster than base Python functions.

In [83]:
hgt = np.round(np.random.normal(1.75, 0.20, 5000), 2)
wgt = np.round(np.random.normal(60.32, 15, 5000), 2)
np_city = np.column_stack((hgt, wgt))

NumPy can also be used to make sample data. In the hgt and wgt variables, the numbers being used are the distribution mean, the distribution standard deviation, and the number of samples. This means that each was sampled 5000 times and then the np.column_stack command to paste the two data sets together as two columns.