Alicia Sigmon
als333@pitt.edu
9/6/2017

# Data Camp Notes
 - Python can't do calculations on lists, so we need numpy
 - numpy arrays must contain 1 type
 - a numpy array is it's own type

# Baseball BMI Example:

In [2]:
#pip3 install numpy
import numpy as np

# Create a numpy array from height: np_height
np_height = np.array([70,75,79,80])

# Convert np_heig<21ht to m: np_height_m
np_height_m=np_height*.0254

# Print np_height_m
print("Height (meters): "+str(np_height_m))

# Write / Print np_weight_kg
np_weight_kg = np.array([150,180,140,190])*.453592
print("Weight (kg): "+str(np_weight_kg))

# Calc. BMI
bmi=np_weight_kg / np_height_m **2

# Write / Print array of people with BMI < 21
light = np.array(bmi<21)
print("Boolean Array of BMI < 21:",str(light))

# Print BMI's of the people with BMI < 21
print("BMI < 21:", str(bmi[light]))


Height (meters): [ 1.778   1.905   2.0066  2.032 ]
Weight (kg): [ 68.0388   81.64656  63.50288  86.18248]
Boolean Array of BMI < 21: [False False  True  True]
BMI < 21: [ 15.77145664  20.87236112]


In [3]:
# True converts to the integer 1, and False convets to the integer 
print(np.array([True, 1, 2]) + np.array([3, 4, False]))
print(np.array([4, 3, 0]) + np.array([0, 2, 2]))

[4 5 2]
[4 5 2]


# 2D NumPy Arrays
 - can still only have 1 type
 - if you make one position a string, all become strings

In [4]:
np_2d = np.array([[1,2,3],
                [4,5,6]])
print(np_2d)
print(np_2d.shape)

np_2d_str = np.array([[1,2,3],
                [4,5,"6"]])
print(np_2d_str)
print(np_2d_str.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[['1' '2' '3']
 ['4' '5' '6']]
(2, 3)


# Baseball: 2D NumPy

In [5]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Already imported numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

# Print out the 2nd row of np_baseball
# This is one player's height and weight
print(np_baseball[1])

# Select the entire second column of np_baseball
    # This is the players' weights: np_weight
    # All of the rows, only the 2nd column
np_weight=np_baseball[:,1]

print(np_weight)

# Print out height of the 4th player
print(np_baseball[3,0])

# Create np_height from np_baseball
    # All of the rows, only the 1st column
np_height=np_baseball[:,0]

<class 'numpy.ndarray'>
(4, 2)
[ 215.   102.7]
[  78.4  102.7   98.5   75.2]
188.0


In [6]:
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
print("np_mat*2 :")
print(np_mat * 2)

print("np_mat + np.array([10,10])")
print(np_mat + np.array([10,10]))

print("np_mat + np_mat")
print(np_mat + np_mat)

np_mat*2 :
[[ 2  4]
 [ 6  8]
 [10 12]]
np_mat + np.array([10,10])
[[11 12]
 [13 14]
 [15 16]]
np_mat + np_mat
[[ 2  4]
 [ 6  8]
 [10 12]]


I believe the above example shows the following:
- np_mat does not change the original unless you set it equal to a new variable
- when you perform actions, it adds within each cell
        

# Statistics with NumPy

In [7]:
# Print out the mean of np_height
avg=np.mean(np_height)
print("Average:",np.mean(np_height))

# Print out the median of np_height
med =np.median(np_height) 
print("Median:",np.median(np_height))

# Print the standard deviation of np_height
stddev = np.std(np_height)
print("Standard Deviation: " + str(stddev))

# Print the correlation between the weight and height.
    # this can be done by looking at our 1D arrays
    # or by slicing from the 2D arrays again
corr = np.corrcoef(np_height,np_weight)
#corr = np.corrcoef(np_baseball[:,0],np_baseball[:,1])
print("Correlation: " + str(corr))


Average: 198.25
Median: 199.0
Standard Deviation: 14.6351460533
Correlation: [[ 1.          0.95865738]
 [ 0.95865738  1.        ]]


In [8]:
# You can index by the columns
shorter = np_baseball[np_weight!=102.7]
print(shorter)

# In the Data Camp tutorial, positions was an additional column
# so they found the heights and weights of all Goal Keepers 
# and then looked for the median

[[ 180.    78.4]
 [ 210.    98.5]
 [ 188.    75.2]]
