In [9]:
#NH Li, nhl3@pitt.edu, 09/05/17

#numpy_notes

import numpy as np

#example - proficiency tests from time 1 to time 2
#created some lists - these are not real data
jp_prof1 = [20, 25, 30, 25, 23, 24, 29, 30, 21, 22, 21, 29, 30, 22, 30, 25]
jp_prof2 = [22, 24, 35, 26, 28, 28, 30, 30, 20, 19, 20, 25, 30, 28, 30, 26]
ch_prof1 = [18, 19, 30, 28, 29, 27, 28, 21, 19, 23, 22, 23, 17, 29, 20, 21]
ch_prof2 = [21, 18, 32, 30, 27, 28, 29, 22, 24, 20, 22, 28, 20, 29, 24, 23]
sp_prof1 = [21, 22, 21, 27, 29, 24, 25, 21, 26, 19, 30, 27, 21, 25, 21, 20]
sp_prof2 = [25, 24, 25, 26, 29, 24, 28, 20, 22, 20, 27, 30, 24, 28, 22, 22]

#create numpy array from proficency
np_jp1 = np.array(jp_prof1)
np_jp2 = np.array(jp_prof2)
print(type(np_jp1))
print(type(np_jp2))
print(np_jp1)
print(np_jp2)

#print out improvement of proficiency scores from time 1 to time 2
#this will create a list of how much each particiapnt improved in their scores from t1 to t2
t2_improve = np_jp2 - np_jp1
print(t2_improve)

#students who did not improve will need to participate in further classes
moreclass = t2_improve < 0
#printout the score that showed no improvement
print(moreclass)
#print out the score who will have to take more class
print(t2_improve[moreclass])
#now we know how many paricipants failed to improve from the jp data and their score

#now some basic statistics of the data
#find the average and median proficiency scores from t1 to t2 for each L1 background
print('the mean proficiency score of jp1 was', np.mean(np_jp1))
print('the mean proficiency score of jp2 was', np.mean(np_jp2))
print('the median proficiency score of jp1 was', np.median(np_jp1))
print('the median proficiency score of jp2 was', np.median(np_jp2))

#we can also find out as a group whether they all imrpoved or not

jp_t2_improve = np.mean(np_jp2) - np.mean(np_jp1)
print('the japanese learners improved their scores from t1 to t2 by an average of', jp_t2_improve, 'points.')

#standard deviation of scores
jp1stddev = np.std(np_jp1)
jp2stddev = np.std(np_jp2)
print('standard deviation for jp1 was', jp1stddev, 'and standard deviation for jp2 was', jp2stddev)
#this shows that the std deviation was higher in t2 than t1 - so although as a group they improved in scores, there was more variation in t2 than t1 (this is what we can find out)



<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[20 25 30 25 23 24 29 30 21 22 21 29 30 22 30 25]
[22 24 35 26 28 28 30 30 20 19 20 25 30 28 30 26]
[ 2 -1  5  1  5  4  1  0 -1 -3 -1 -4  0  6  0  1]
[False  True False False False False False False  True  True  True  True
 False False False False]
[-1 -1 -3 -1 -4]
the mean proficiency score of jp1 was 25.375
the mean proficiency score of jp2 was 26.3125
the median proficiency score of jp1 was 25.0
the median proficiency score of jp2 was 27.0
the japanese learners improved their scores from t1 to t2 by an average of 0.9375 points.
standard deviation for jp1 was 3.62068708949 and standard deviation for jp2 was 4.31159410775
