In [1]:
#NH Li, nhl3@pitt.edu, 09/05/17

#numpy_notes

import numpy as np

#example - proficiency tests from time 1 to time 2
#created some lists - these are not real data
jp_prof1 = [20, 25, 30, 25, 23]
jp_prof2 = [22, 24, 35, 26, 28]
ch_prof1 = [18, 19, 30, 28, 29]
ch_prof2 = [21, 18, 32, 30, 27]
sp_prof1 = [21, 22, 21, 27, 29]
sp_prof2 = [25, 24, 25, 26, 29]

#create numpy array from proficency
np_jp1 = np.array(jp_prof1)
np_jp2 = np.array(jp_prof2)
print(type(np_jp1))
print(type(np_jp2))
print(np_jp1)
print(np_jp2)

#print out improvement of proficiency scores from time 1 to time 2
#this will create a list of how much each particiapnt improved in their scores from t1 to t2
t2_improve = np_jp2 - np_jp1
print(t2_improve)

#students who did not improve will need to participate in further classes
moreclass = t2_improve < 0
#printout the score that showed no improvement
print(moreclass)
#print out the score who will have to take more class
print(t2_improve[moreclass])
#now we know how many paricipants failed to improve from the jp data and their score

#now some basic statistics of the data
#find the average proficiency score from t1 to t2 for each L1 background




<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[20 25 30 25 23]
[22 24 35 26 28]
[ 2 -1  5  1  5]
[False  True False False False]
[-1]
