NumPy Data Camp notes

- no calculations on list in python
- NumPy = Numeric Python
- Numpy Array = alternative to Python list

In [1]:
#Example data:

height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]

In [8]:
#start by:

import numpy as np

#covert lists to np.array

np_height = np.array(height)
np_weight = np.array(weight)

print(np_height)
print(np_weight)

#np array must contain only one type (list, string, etc.)

[ 1.73  1.68  1.71  1.89  1.79]
[ 65.4  59.2  63.6  88.4  68.7]


In [12]:
#different methods than python lists - python can't do this:

bmi = np_weight/np_height **2
print(bmi)

#called element by sum of arrays

[ 21.85171573  20.97505669  21.75028214  24.7473475   21.44127836]


In [14]:
#indices work the same

bmi[1]

#or with booleans

bmi > 23

array([False, False, False,  True, False], dtype=bool)

In [15]:
#good for vector arithmetic
#making lists contain same types of items is called 'list coersion'

#True = 1, False = 0

np.array([True, 1, 2]) + np.array([3, 4, False])

#lists and subsets (splices) work the same way as in python

array([4, 5, 2])

2D Numpy Arrays
- good for tables
- call array.shape to get 2d shape
- : in index means 'include all rows', e.g. np_x[:,0]

In [18]:
#Example:

import numpy as np
np_mat = np.array([[1, 2],
                  [3, 4],
                  [5, 6]])
print(np_mat * 2)
print(np_mat[:,0])    

[[ 2  4]
 [ 6  8]
 [10 12]]
[1 3 5]


Basic statistics
- summarizing statistics
- np.mean, np.median (for averages)
- np.std (standard deviation)
- np.corrcoef (correlate coefficient) - takes two arguments, e.g.np.corrcoef(np_array[:,0], np_array[:,1])

Data Science Handbook - additional notes
- examples of different possible dimensions:

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

- lots of other attributes to look at
- NumPy much faster than loops

In [22]:
#new way of slicing (for me) to jump elements:

x[::2]  # every other element

array([0, 2, 4, 6, 8])

ufuncs = lots of different arithemetic options, mostly beyond my need or understanding

Broadcasting = rules for combining arrays:

Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.

Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

**Study more and talk to Na-Rae - limited understanding of examples**

In [23]:
M = np.ones((2, 3))
a = np.arange(3)

print(M.shape)
print(a.shape)

(2, 3)
(3,)


In [24]:
M + a

array([[ 1.,  2.,  3.],
       [ 1.,  2.,  3.]])