Andrew Ryan

AndrewRyan@pitt.edu

9/7/2017

In [134]:
import numpy as np
print("Numpy version", np.__version__)

Numpy version 1.12.1


In [135]:
np.array([range(i,i * 2) for i in [1, 3, 5]])

array([range(1, 2), range(3, 6), range(5, 10)], dtype=object)

Why does it print out dtype when multiplying? **Above vs Below**

In [136]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [137]:
np.full((4, 3), "cat")

array([['cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat']], 
      dtype='<U3')

In [138]:
np.arange(0, 25, 2.5)

array([  0. ,   2.5,   5. ,   7.5,  10. ,  12.5,  15. ,  17.5,  20. ,  22.5])

In [139]:
np.random.random((4,6))

array([[ 0.41447223,  0.99254779,  0.31542987,  0.56157661,  0.51535789,
         0.92853759],
       [ 0.45677992,  0.11818774,  0.81280997,  0.1911384 ,  0.82187354,
         0.77465406],
       [ 0.95521207,  0.64007534,  0.66400369,  0.57571795,  0.50360328,
         0.7855015 ],
       [ 0.08209985,  0.03044421,  0.58147842,  0.54100766,  0.18296672,
         0.40410203]])

In [140]:
foo = np.random.randint(100, size=(3, 3))
foo

array([[ 4, 88,  4],
       [47, 62, 82],
       [86, 99, 74]])

In [141]:
print("Center number is", foo[1,1])

Center number is 62


x[start:stop:step]

- If step is negative, list is reversed

In [142]:
foo2  = foo[:2,:2]
foo2

array([[ 4, 88],
       [47, 62]])

In [143]:
foo[0,0] = 100
foo2

array([[100,  88],
       [ 47,  62]])

In [147]:
foo3 = foo2.copy()
foo3[0,0] = 0
print(foo3,"\n")
print(foo)

[[ 0 88]
 [47 62]] 

[[100  88   4]
 [ 47  62  82]
 [ 86  99  74]]


In [150]:
np.arange(1,26).reshape((5,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [153]:
np.concatenate([foo2,foo3])

array([[100,  88],
       [ 47,  62],
       [  0,  88],
       [ 47,  62]])