# Class Activity 2: `numpy` Practice
9/7/2017

## (1) Data comes in many forms! 

- Build a numpy array called `exams` from the string below. 
- There are three students (rows) and their five exam scores (columns). 
- String methods such as `.split()` will come in handy. 
- You will also want to pay attention to object types: string vs. integer


In [1]:
teacher_notes = """lisa: 90, 99, 100, 95, 95
bart: 70, 82, 65, 53, 77
nelson: 80, 85, 85, 88, 84
"""
print(teacher_notes)

lisa: 90, 99, 100, 95, 95
bart: 70, 82, 65, 53, 77
nelson: 80, 85, 85, 88, 84



In [2]:
# My Code:

#after each student's last exam, there is a \n
teacher_notes

lists = []

#to get rid of the final \n, use .strip() <-- removes whitespace characters on either end
for l in teacher_notes.strip().split('\n'):
    
    #split on : to get name separated from first number
    scores = l.replace(":",",").split(', ')
    #print(scores)
    #print(scores[1:])
    
    #ignores first item, and uses list comprehension to turn strings into integers
    numbers = [int(x) for x in scores[1:]]
    #print(numbers)
    
    #put all the lists in the empty list "lists"
    lists.append(numbers)
#print(lists)

import numpy as np
exams = np.array(lists)
print(exams)

[[ 90  99 100  95  95]
 [ 70  82  65  53  77]
 [ 80  85  85  88  84]]


## (2) Accessing `exams` numpy array
- Get Bart's exam scores
- Get Nelson's exam scores
- Get Lisa's 3rd exam score
- Get Lisa's exam scores, without the last one
- Get Bart's and Nelson's exam scores

In [3]:
# My Code:

#bart
exams[1,:]
exams[1]      #same as above -- if only one index, it assumes rows
#nelson
exams[-1,:]
#lisa exam 3
exams[0,2]
#lisa without last exam
exams[0,:-1]
#bart&nelson
exams[1:,:]
exams[[1,2],:]    #same as above, using explicit indexing

array([[70, 82, 65, 53, 77],
       [80, 85, 85, 88, 84]])

## (3) Statistics with `numpy`
- What is Lisa's exam average? What is Bart's?
- What is Lisa's maximum exam score? Minimum?
- What is the total of Lisa's exam scores?
- What is the average of the last exam? 
- What is the average of each student? (Use `for` loop!)

In [4]:
# My Code:

#lisa average
print(exams[0].mean())

#bart's average
print(exams[1].mean())

#lisa's max & min
print(exams[0].max())
print(exams[0].min())

#lisa's total
print(exams[0].sum())
#print(sum(exams[0]))       # a lot slower than numpy sum

#last exam average
print(exams[:,-1].mean())

#average per student 
for x in exams:
    print(x)
    print(x.mean())

95.8
69.4
100
90
479
85.3333333333
[ 90  99 100  95  95]
95.8
[70 82 65 53 77]
69.4
[80 85 85 88 84]
84.4


## (4) Manipulating an array
- Teacher is having a good day. She decides to boost every exam score by 5. 
- Teacher is having a bad day. She takes 10 points off of everyone's last exam. 
- Teacher is having an even worse day. She decides to assign 0 to everyone's last exam. 

** Pay attention to the original `exams` array. Is it changing, or are you creating a new array?

In [5]:
# My Code:

exams+=5   #adds 5 to original
exams-=5   #subtracts 5 to get back to original
print(exams)

#10 off last exam
exams[:,-1] -= 10
print(exams)

exams[:,-1] = 0
print(exams)

[[ 90  99 100  95  95]
 [ 70  82  65  53  77]
 [ 80  85  85  88  84]]
[[ 90  99 100  95  85]
 [ 70  82  65  53  67]
 [ 80  85  85  88  74]]
[[ 90  99 100  95   0]
 [ 70  82  65  53   0]
 [ 80  85  85  88   0]]


In [6]:
milhouse = [85, 90, 90, 70, 55]
# Your code below. 

## (6) Transforming content
- Teacher wants to convert numeric scores to letter grades. 
- First, build a function called `letter_grade()` which takes a numeric score and returns 'A', 'B', 'C', 'D', or 'F'. 
- Then, apply this function to each element in `exam`. (Hint: use `numpy.vectorize()`)

In [7]:
# Your code here. 