# Class Activity 2: `numpy` Practice
9/7/2017

## (1) Data comes in many forms! 

- Build a numpy array called `exams` from the string below. 
- There are three students (rows) and their five exam scores (columns). 
- String methods such as `.split()` will come in handy. 
- You will also want to pay attention to object types: string vs. integer


In [1]:
teacher_notes = """lisa: 90, 99, 100, 95, 95
bart: 70, 82, 65, 53, 77
nelson: 80, 85, 85, 88, 84
"""
print(teacher_notes)
teacher_notes

lisa: 90, 99, 100, 95, 95
bart: 70, 82, 65, 53, 77
nelson: 80, 85, 85, 88, 84



'lisa: 90, 99, 100, 95, 95\nbart: 70, 82, 65, 53, 77\nnelson: 80, 85, 85, 88, 84\n'

In [2]:
lists = []           # initialize an empty list, will populate later

for l in teacher_notes.strip().split('\n'):   # get rid of last '\n' and split
    scores = l.replace(':', ",").split(', ')  # change : to , and split
    #print(scores)
    numbers = [int(x) for x in scores[1:]]    # drop 1st entry (name), integerfy
    #print(numbers)
    lists.append(numbers)                     # put into lists               

print(lists)    # print lists, looks good
lists           # does nothing, only last object evaluated will be returned as Out[]

import numpy as np
exams = np.array(lists)
exams                       # success!

[[90, 99, 100, 95, 95], [70, 82, 65, 53, 77], [80, 85, 85, 88, 84]]


array([[ 90,  99, 100,  95,  95],
       [ 70,  82,  65,  53,  77],
       [ 80,  85,  85,  88,  84]])

## (2) Accessing `exams` numpy array
- Get Bart's exam scores
- Get Nelson's exam scores
- Get Lisa's 3rd exam score
- Get Lisa's exam scores, without the last one
- Get Bart's and Nelson's exam scores

In [3]:
# Note: again, only the very last line will be returned as an output. 
# Everything above will need to be passed to print() in order to show up. 

exams[1]               # Bart
exams[-1]              # Nelson, same as exams[2]
exams[0, 2]         # Lisa's 3rd exam
exams[0, :-1]       # same as exams[0, :4]
exams[[1,2], :]     # same as exams[1:, :]

array([[70, 82, 65, 53, 77],
       [80, 85, 85, 88, 84]])

## (3) Statistics with `numpy`
- What is Lisa's exam average? What is Bart's?
- What is Lisa's maximum exam score? Minimum?
- What is the total of Lisa's exam scores?
- What is the average of the last exam? 
- What is the average of each student? (Use `for` loop!)

In [4]:
exams[0].sum()      # faster!
sum(exams[0])       # same, but slower

exams[0].max(), exams[0].min()

exams[:, -1].mean()

for x in exams:
    print(x, x.mean())

[ 90  99 100  95  95] 95.8
[70 82 65 53 77] 69.4
[80 85 85 88 84] 84.4


## (4) Manipulating an array
- Teacher is having a good day. She decides to boost every exam score by 5. 
- Teacher is having a bad day. She takes 10 points off of everyone's last exam. 
- Teacher is having an even worse day. She decides to assign 0 to everyone's last exam. 

** Pay attention to the original `exams` array. Is it changing, or are you creating a new array?

In [5]:
exams + 5  # returns a new array, original array not changed
print(exams)

exams[:, -1] -= 10   # NOW this changes the exams array
print(exams)

exams[:, -1] = 0     # likewise
print(exams)

[[ 90  99 100  95  95]
 [ 70  82  65  53  77]
 [ 80  85  85  88  84]]
[[ 90  99 100  95  85]
 [ 70  82  65  53  67]
 [ 80  85  85  88  74]]
[[ 90  99 100  95   0]
 [ 70  82  65  53   0]
 [ 80  85  85  88   0]]


## (5) Adding to existing array
- Oops, teacher forgot about Milhouse's exam scores. 
- How to add them into `exams`?
- Hint: use `np.append()`

In [6]:
milhouse = [85, 90, 90, 70, 55]
np.append(exams, milhouse)      # nope, does not work. array flattened

array([ 90,  99, 100,  95,   0,  70,  82,  65,  53,   0,  80,  85,  85,
        88,   0,  85,  90,  90,  70,  55])

In [7]:
help(np.append)     # let's find out how this method works

Help on function append in module numpy.lib.function_base:

append(arr, values, axis=None)
    Append values to the end of an array.
    
    Parameters
    ----------
    arr : array_like
        Values are appended to a copy of this array.
    values : array_like
        These values are appended to a copy of `arr`.  It must be of the
        correct shape (the same shape as `arr`, excluding `axis`).  If
        `axis` is not specified, `values` can be any shape and will be
        flattened before use.
    axis : int, optional
        The axis along which `values` are appended.  If `axis` is not
        given, both `arr` and `values` are flattened before use.
    
    Returns
    -------
    append : ndarray
        A copy of `arr` with `values` appended to `axis`.  Note that
        `append` does not occur in-place: a new array is allocated and
        filled.  If `axis` is None, `out` is a flattened array.
    
    See Also
    --------
    insert : Insert elements into an array.


In [8]:
# Ah, so milhouse should be turned into a two-dimensional array, and axis must be specified
np.append(exams, [milhouse], axis=0)        # SUCCESS! 

array([[ 90,  99, 100,  95,   0],
       [ 70,  82,  65,  53,   0],
       [ 80,  85,  85,  88,   0],
       [ 85,  90,  90,  70,  55]])

In [9]:
exams = np.append(exams, [milhouse], axis=0)   # append permanently
exams

array([[ 90,  99, 100,  95,   0],
       [ 70,  82,  65,  53,   0],
       [ 80,  85,  85,  88,   0],
       [ 85,  90,  90,  70,  55]])

## (6) Transforming content
- Teacher wants to convert numeric scores to letter grades. 
- First, build a function called `letter_grade()` which takes a numeric score and returns 'A', 'B', 'C', 'D', or 'F'. 
- Then, apply this function to each element in `exam`. (Hint: use `numpy.vectorize()`)

In [10]:
def letter_grade(score):
    if score >=90: return 'A'
    elif score >=80: return 'B'
    elif score >=70: return 'C'
    elif score >=60: return 'D'
    else: return 'F'

In [11]:
letter_grade(87)     # works! 

'B'

In [12]:
letter_grade(exams)  # Nope. function is not array-aware.

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [13]:
# Build a vectorized version of the function, which can operate on an array
letter_grade_vec = np.vectorize(letter_grade)

# Now this function can accept an array as input
letter_grade_vec(exams)

array([['A', 'A', 'A', 'A', 'F'],
       ['C', 'B', 'D', 'F', 'F'],
       ['B', 'B', 'B', 'B', 'F'],
       ['B', 'A', 'A', 'C', 'F']],
      dtype='<U1')