# Class Activity 2: `numpy` Practice
9/7/2017

## (1) Data comes in many forms! 

- Build a numpy array called `exams` from the string below. 
- There are three students (rows) and their five exam scores (columns). 
- String methods such as `.split()` will come in handy. 
- You will also want to pay attention to object types: string vs. integer


In [11]:
teacher_notes = """lisa: 90, 99, 100, 95, 95
bart: 70, 82, 65, 53, 77
nelson: 80, 85, 85, 88, 84
"""
teacher_notes

'lisa: 90, 99, 100, 95, 95\nbart: 70, 82, 65, 53, 77\nnelson: 80, 85, 85, 88, 84\n'

In [14]:
# Your code here. 
lists = []
for l in teacher_notes.strip().split('\n'):
    scores = l.replace(':',",").split(', ')
    #print(scores)
    numbers = [int(x) for x in scores[1:]]
    #print(numbers)
    lists.append(numbers)
#print(lists)
lists

import numpy as np
exams = np.array(lists)
exams

array([[ 90,  99, 100,  95,  95],
       [ 70,  82,  65,  53,  77],
       [ 80,  85,  85,  88,  84]])

## (2) Accessing `exams` numpy array
- Get Bart's exam scores
- Get Nelson's exam scores
- Get Lisa's 3rd exam score
- Get Lisa's exam scores, without the last one
- Get Bart's and Nelson's exam scores

In [15]:
# Your code here.
#Bart's exams
bart = exams[1]

#Nelson's exams
nelson = exams[2]                    #same as exams[-1]

#Lisa's 3rd exam score
lisa_3 = exams[0,2]

#Lisa's scores without last
lisa_except_last = exams [0,:-1]     #same as exams[0, :5]

#Bart and Nelson's scores
bart_nelson = exams[1:,:]            #same as exams[[1,2],:]

#print
print(bart)
print(nelson)
print(lisa_3)
print(lisa_except_last)
print(bart_nelson)

[70 82 65 53 77]
[80 85 85 88 84]
100
[ 90  99 100  95]
[[70 82 65 53 77]
 [80 85 85 88 84]]


## (3) Statistics with `numpy`
- What is Lisa's exam average? What is Bart's?
- What is Lisa's maximum exam score? Minimum?
- What is the total of Lisa's exam scores?
- What is the average of the last exam? 
- What is the average of each student? (Use `for` loop!)

In [16]:
# Your code here. 
#Lisa average
lisa_avg = exams[0].mean()

#Bart's average
bart_avg = exams[1].mean()

#Lisa's max and min
lmax = exams[0].max()
lmin = exams[0].min()

#Lisa total
ltotal = exams[0].sum()

#Last average
last_avg = exams[:,-1].mean()

#Student averages
for x in exams:
    print(x, x.mean())

#print everything
print(lisa_avg)
print(bart_avg)
print(lmax)
print(lmin)
print(ltotal)
print(last_avg)


[ 90  99 100  95  95] 95.8
[70 82 65 53 77] 69.4
[80 85 85 88 84] 84.4
95.8
69.4
100
90
479
85.3333333333


## (4) Manipulating an array
- Teacher is having a good day. She decides to boost every exam score by 5. 
- Teacher is having a bad day. She takes 10 points off of everyone's last exam. 
- Teacher is having an even worse day. She decides to assign 0 to everyone's last exam. 

** Pay attention to the original `exams` array. Is it changing, or are you creating a new array?

In [24]:
# Your code here. 
exams += 5
print(exams)
exams -= 5
exams[:,-1] -= 10
print(exams)
exams[:,-1] += 10
exams[:,-1] = 0
print(exams)

#IT ISN'T DOING A WORK WHYYYY

[[ 95 104 105 100   5]
 [ 75  87  70  58   5]
 [ 85  90  90  93   5]]
[[ 90  99 100  95 -10]
 [ 70  82  65  53 -10]
 [ 80  85  85  88 -10]]
[[ 90  99 100  95   0]
 [ 70  82  65  53   0]
 [ 80  85  85  88   0]]


## (5) Adding to existing array
- Oops, teacher forgot about Milhouse's exam scores. 
- How to add them into `exams`?
- Hint: use `np.append()`

In [ ]:
milhouse = [85, 90, 90, 70, 55]
# Your code below. 

## (6) Transforming content
- Teacher wants to convert numeric scores to letter grades. 
- First, build a function called `letter_grade()` which takes a numeric score and returns 'A', 'B', 'C', 'D', or 'F'. 
- Then, apply this function to each element in `exam`. (Hint: use `numpy.vectorize()`)

In [ ]:
# Your code here. 