Alicia Sigmon, als333@pitt.edu, 10/14/2017
# To Do 9

In [28]:
from sklearn import datasets
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('ggplot')
import nltk

In [21]:
# Show all output
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [27]:
# Turn off pretty printing of jupyter notebook... it generates long lines
%pprint

Pretty printing has been turned OFF


In [3]:
import sklearn
from sklearn.datasets import load_files

In [5]:
movie_dir=r"C:\Users\sigmo\Dropbox\Documents\School\PITT\Previous Semesters\Python\nltk_data\corpora\movie_reviews"

In [8]:
movie_train=load_files(movie_dir,shuffle=True)

In [14]:
dir(movie_train)

['DESCR', 'data', 'filenames', 'target', 'target_names']

In [11]:
len(movie_train)
len(movie_train.data)

2000

In [13]:
# Russel Crowe movie
movie_train.data[][:500]

b"good films are hard to find these days . \ngreat films are beyond rare . \nproof of life , russell crowe's one-two punch of a deft kidnap and rescue thriller , is one of those rare gems . \na taut drama laced with strong and subtle acting , an intelligent script , and masterful directing , together it delivers something virtually unheard of in the film industry these days , genuine motivation in a story that rings true . \nconsider the strange coincidence of russell crowe's character in proof of lif"

In [15]:
len(movie_train.filenames)

2000

In [18]:
movie_train.filenames[:2]
# The first file is negative and the second file is positive

array([ 'C:\\Users\\sigmo\\Dropbox\\Documents\\School\\PITT\\Previous Semesters\\Python\\nltk_data\\corpora\\movie_reviews\\neg\\cv405_21868.txt',
       'C:\\Users\\sigmo\\Dropbox\\Documents\\School\\PITT\\Previous Semesters\\Python\\nltk_data\\corpora\\movie_reviews\\pos\\cv190_27052.txt'], 
      dtype='<U122')

In [25]:
movie_train.target[0]
movie_train.target[1]
movie_train.target[2]
# 0 is negative, and 1 is positive

0

1

1

In [24]:
movie_train.target_names[0]
movie_train.target_names[1]
# lists whether positive or negative

'neg'

'pos'

## CountVectorizer & TF-IDF

In [26]:
# import CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer

In [29]:
sents=["The ants go marching one by one, horrah, horrah.",
      "Oh, the little old lady swallowed a fly.",
      "How sweet it is to be loved by you!"]

In [30]:
# Initialize a CoutVectorizer to use NLTK's tokenizer instead of its 
# default one (which ignores punctuation and stopwords). 
# Minimum document frequency set to 1. 
foovec = CountVectorizer(min_df=1, tokenizer=nltk.word_tokenize)

In [31]:
# sents turned into sparse vector of word frequency counts
sents_counts = foovec.fit_transform(sents)
# foovec now contains vocab dictionary which maps unique words to indexes
foovec.vocabulary_

{'the': 22, 'ants': 4, 'go': 8, 'marching': 16, 'one': 19, 'by': 6, ',': 1, 'horrah': 9, '.': 2, 'oh': 17, 'little': 14, 'old': 18, 'lady': 13, 'swallowed': 20, 'a': 3, 'fly': 7, 'how': 10, 'sweet': 21, 'it': 12, 'is': 11, 'to': 23, 'be': 5, 'loved': 15, 'you': 24, '!': 0}

In [32]:
dir(sents_counts)

['__abs__', '__add__', '__array_priority__', '__bool__', '__class__', '__delattr__', '__dict__', '__dir__', '__div__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__idiv__', '__imul__', '__init__', '__init_subclass__', '__isub__', '__iter__', '__itruediv__', '__le__', '__len__', '__lt__', '__matmul__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__numpy_ufunc__', '__pow__', '__radd__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__rmatmul__', '__rmul__', '__rsub__', '__rtruediv__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '_arg_min_or_max', '_arg_min_or_max_axis', '_binopt', '_boolean_index_to_array', '_check_boolean', '_check_ellipsis', '_cs_matrix__get_has_canonical_format', '_cs_matrix__get_sorted', '_cs_matrix__set_has_canonical_format', '_cs_matrix__set_sorted', '_deduped_data', '_d

In [33]:
sents_counts.shape

(3, 25)

In [34]:
sents_counts.toarray()

array([[0, 2, 1, 0, 1, 0, 1, 0, 1, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0,
        1, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
        1, 0, 0],
       [1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
        0, 1, 1]], dtype=int64)

In [35]:
# Convert raw frequency counts into TF-IDF (Term Frequency -- Inverse Document Frequency) values
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer()
sents_tfidf = tfidf_transformer.fit_transform(sents_counts)

In [36]:
# TF-IDF values
# raw counts have been normalized against document length, 
# terms that are found across many docs are weighted down
sents_tfidf.toarray()

array([[ 0.        ,  0.39209658,  0.19604829,  0.        ,  0.25777994,
         0.        ,  0.19604829,  0.        ,  0.25777994,  0.51555988,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.25777994,  0.        ,  0.        ,  0.51555988,
         0.        ,  0.        ,  0.19604829,  0.        ,  0.        ],
       [ 0.        ,  0.25732238,  0.25732238,  0.338348  ,  0.        ,
         0.        ,  0.        ,  0.338348  ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.338348  ,  0.338348  ,
         0.        ,  0.        ,  0.338348  ,  0.338348  ,  0.        ,
         0.338348  ,  0.        ,  0.25732238,  0.        ,  0.        ],
       [ 0.32311233,  0.        ,  0.        ,  0.        ,  0.        ,
         0.32311233,  0.24573525,  0.        ,  0.        ,  0.        ,
         0.32311233,  0.32311233,  0.32311233,  0.        ,  0.        ,
         0.32311233,  0.        ,  0.        ,  0

## Movies Continued

In [37]:
# initialize movie_vector object, and then turn movie train data into a vector 
movie_vec = CountVectorizer(min_df=2, tokenizer=nltk.word_tokenize)         # use all 25K words. 82.2% acc.
# movie_vec = CountVectorizer(min_df=2, tokenizer=nltk.word_tokenize, max_features = 3000) # use top 3000 words only. 78.5% acc.
movie_counts = movie_vec.fit_transform(movie_train.data)

# Based on the previously written stats, we want to use all of the words because the accuracy is higher
# but 82.5% isn't very good still.

In [38]:
dir(movie_vec)

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_char_ngrams', '_char_wb_ngrams', '_check_vocabulary', '_count_vocab', '_get_param_names', '_limit_features', '_sort_features', '_validate_vocabulary', '_white_spaces', '_word_ngrams', 'analyzer', 'binary', 'build_analyzer', 'build_preprocessor', 'build_tokenizer', 'decode', 'decode_error', 'dtype', 'encoding', 'fit', 'fit_transform', 'fixed_vocabulary_', 'get_feature_names', 'get_params', 'get_stop_words', 'input', 'inverse_transform', 'lowercase', 'max_df', 'max_features', 'min_df', 'ngram_range', 'preprocessor', 'set_params', 'stop_words', 'stop_words_', 'strip_accents', 'token_pattern', 'tokenizer', 'transform'

In [39]:
movie_vec.get_stop_words

<bound method VectorizerMixin.get_stop_words of CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=2,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=<function word_tokenize at 0x0000024BCF340620>,
        vocabulary=None)>

In [44]:
# .vocabulary_.get() returns an index
movie_vec.vocabulary_.get('screen') #19637
movie_vec.vocabulary_.get('the') #22570
movie_vec.vocabulary_.get('schwarzenegger') #19574

19637

22570

19574

In [45]:
# .shape gives dimensions
movie_counts.shape
# the dimensions are very large: 2000x25313
    # 1st dimension is number of docs, 2nd dimension is unique words

(2000, 25313)

In [46]:
# Convert raw frequency counts into TF-IDF values
tfidf_transformer = TfidfTransformer()
movie_tfidf = tfidf_transformer.fit_transform(movie_counts)

In [48]:
# doesn't change dimensions, but how tf-idf values instead of raw freq counts
movie_tfidf.shape

(2000, 25313)

## Naive Bayes

In [49]:
# Now ready to build a classifier. 
# We will use Multinominal Naive Bayes as our model
from sklearn.naive_bayes import MultinomialNB

In [50]:
# Split data into training and test sets
# from sklearn.cross_validation import train_test_split  # deprecated in 0.18
from sklearn.model_selection import train_test_split
docs_train, docs_test, y_train, y_test = train_test_split(
    movie_tfidf, movie_train.target, test_size = 0.20, random_state = 12)

In [51]:
# Train a Multimoda Naive Bayes classifier
clf = MultinomialNB().fit(docs_train, y_train)

In [52]:
# Predicting the test set results and finding accuracy
y_pred = clf.predict(docs_test)
sklearn.metrics.accuracy_score(y_test, y_pred)

0.82250000000000001

In [53]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[176,  30],
       [ 41, 153]])

## Try Classifier on Fake Movie Reviews

In [54]:
# very short and fake movie reviews
reviews_new = ['This movie was excellent', 'Absolute joy ride', 
            'Steven Seagal was terrible', 'Steven Seagal shined through.', 
              'This was certainly a movie', 'Two thumbs up', 'I fell asleep halfway through', 
              "We can't wait for the sequel!!", '!', '?', 'I cannot recommend this highly enough', 
              'instant classic.', 'Steven Seagal was amazing. His performance was Oscar-worthy.']
reviews_new_counts = movie_vec.transform(reviews_new)
reviews_new_tfidf = tfidf_transformer.transform(reviews_new_counts)

In [55]:
# classifier's prediction
pred=clf.predict(reviews_new_tfidf)

In [57]:
# printing results
for review, category in zip(reviews_new,pred):
    print('%r => %s' % (review, movie_train.target_names[category]))
# predicts a lot of negative reviews...

'This movie was excellent' => pos
'Absolute joy ride' => pos
'Steven Seagal was terrible' => neg
'Steven Seagal shined through.' => neg
'This was certainly a movie' => neg
'Two thumbs up' => neg
'I fell asleep halfway through' => neg
"We can't wait for the sequel!!" => neg
'!' => neg
'?' => neg
'I cannot recommend this highly enough' => pos
'instant classic.' => pos
'Steven Seagal was amazing. His performance was Oscar-worthy.' => neg
