Alicia Sigmon, als333@pitt.edu, 10/14/2017
# To Do 9

In [2]:
import nltk
import matplotlib.pyplot as plt
import seaborn as sns  

In [3]:
# Show all output
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [4]:
# Turn off pretty printing of jupyter notebook... it generates long lines
%pprint

Pretty printing has been turned OFF


In [5]:
import sklearn
from sklearn.datasets import load_files

In [6]:
movie_dir=r"C:\Users\sigmo\Dropbox\Documents\School\PITT\Previous Semesters\Python\nltk_data\corpora\movie_reviews"

In [7]:
movie_train=load_files(movie_dir,shuffle=True)

In [8]:
dir(movie_train)

['DESCR', 'data', 'filenames', 'target', 'target_names']

In [9]:
len(movie_train)
len(movie_train.data)

5

2000

In [10]:
# Russel Crowe movie
movie_train.data[1][:500]

b"good films are hard to find these days . \ngreat films are beyond rare . \nproof of life , russell crowe's one-two punch of a deft kidnap and rescue thriller , is one of those rare gems . \na taut drama laced with strong and subtle acting , an intelligent script , and masterful directing , together it delivers something virtually unheard of in the film industry these days , genuine motivation in a story that rings true . \nconsider the strange coincidence of russell crowe's character in proof of lif"

In [11]:
len(movie_train.filenames)

2000

In [12]:
movie_train.filenames[:2]
# The first file is negative and the second file is positive

array([ 'C:\\Users\\sigmo\\Dropbox\\Documents\\School\\PITT\\Previous Semesters\\Python\\nltk_data\\corpora\\movie_reviews\\neg\\cv405_21868.txt',
       'C:\\Users\\sigmo\\Dropbox\\Documents\\School\\PITT\\Previous Semesters\\Python\\nltk_data\\corpora\\movie_reviews\\pos\\cv190_27052.txt'], 
      dtype='<U122')

In [13]:
movie_train.target[0]
movie_train.target[1]
movie_train.target[2]
# 0 is negative, and 1 is positive

0

1

1

In [14]:
movie_train.target_names[0]
movie_train.target_names[1]
# lists whether positive or negative

'neg'

'pos'

## CountVectorizer & TF-IDF

In [15]:
# import CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer

In [16]:
sents=["The ants go marching one by one, horrah, horrah.",
      "Oh, the little old lady swallowed a fly.",
      "How sweet it is to be loved by you!"]

In [17]:
# Initialize a CoutVectorizer to use NLTK's tokenizer instead of its 
# default one (which ignores punctuation and stopwords). 
# Minimum document frequency set to 1. 
foovec = CountVectorizer(min_df=1, tokenizer=nltk.word_tokenize)

In [18]:
# sents turned into sparse vector of word frequency counts
sents_counts = foovec.fit_transform(sents)
# foovec now contains vocab dictionary which maps unique words to indexes
foovec.vocabulary_   #words are mapped to their index key, beacuse the indices take up less space

{'the': 22, 'ants': 4, 'go': 8, 'marching': 16, 'one': 19, 'by': 6, ',': 1, 'horrah': 9, '.': 2, 'oh': 17, 'little': 14, 'old': 18, 'lady': 13, 'swallowed': 20, 'a': 3, 'fly': 7, 'how': 10, 'sweet': 21, 'it': 12, 'is': 11, 'to': 23, 'be': 5, 'loved': 15, 'you': 24, '!': 0}

In [19]:
dir(sents_counts)

['__abs__', '__add__', '__array_priority__', '__bool__', '__class__', '__delattr__', '__dict__', '__dir__', '__div__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__idiv__', '__imul__', '__init__', '__init_subclass__', '__isub__', '__iter__', '__itruediv__', '__le__', '__len__', '__lt__', '__matmul__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__numpy_ufunc__', '__pow__', '__radd__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__rmatmul__', '__rmul__', '__rsub__', '__rtruediv__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '_arg_min_or_max', '_arg_min_or_max_axis', '_binopt', '_boolean_index_to_array', '_check_boolean', '_check_ellipsis', '_cs_matrix__get_has_canonical_format', '_cs_matrix__get_sorted', '_cs_matrix__set_has_canonical_format', '_cs_matrix__set_sorted', '_deduped_data', '_d

In [20]:
sents_counts.shape
# 3 sentences, 25 unique words, or "features"

(3, 25)

In [21]:
sents_counts.toarray() #2D array
# each sentence is a list in the array, and for each word in the 3 sentences
# there is a count for how many times that word appears in each sentence

# index 0 is an exclamation <-- it only occurs once in the 3rd document and not in the other sentences or "documents"

array([[0, 2, 1, 0, 1, 0, 1, 0, 1, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0,
        1, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
        1, 0, 0],
       [1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
        0, 1, 1]], dtype=int64)

In [22]:
# Convert raw frequency counts into TF-IDF (Term Frequency -- Inverse Document Frequency) values
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer()
sents_tfidf = tfidf_transformer.fit_transform(sents_counts)

#used to normalize <-- words like is will be common in all docs
# idf <-- how common a word is across all documents (here the docs are sentences)

# TF(t)=(#times t in doc)/(total# t in doc)
# IDF(t)= log_e((Total#docs)/(#docs with term t))


# the same raw counts will be different in TFDIF;
    # terms that are more common across docs are weighed down

In [23]:
# TF-IDF values
# raw counts have been normalized against document length, 
# terms that are found across many docs are weighted down
sents_tfidf.toarray()
# no longer just a frequency count

array([[ 0.        ,  0.39209658,  0.19604829,  0.        ,  0.25777994,
         0.        ,  0.19604829,  0.        ,  0.25777994,  0.51555988,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.25777994,  0.        ,  0.        ,  0.51555988,
         0.        ,  0.        ,  0.19604829,  0.        ,  0.        ],
       [ 0.        ,  0.25732238,  0.25732238,  0.338348  ,  0.        ,
         0.        ,  0.        ,  0.338348  ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.338348  ,  0.338348  ,
         0.        ,  0.        ,  0.338348  ,  0.338348  ,  0.        ,
         0.338348  ,  0.        ,  0.25732238,  0.        ,  0.        ],
       [ 0.32311233,  0.        ,  0.        ,  0.        ,  0.        ,
         0.32311233,  0.24573525,  0.        ,  0.        ,  0.        ,
         0.32311233,  0.32311233,  0.32311233,  0.        ,  0.        ,
         0.32311233,  0.        ,  0.        ,  0

## Movies Continued

In [24]:
# initialize movie_vector object, and then turn movie train data into a vector 
movie_vec = CountVectorizer(min_df=2, tokenizer=nltk.word_tokenize)         # use all 25K words. 82.2% acc.
# movie_vec = CountVectorizer(min_df=2, tokenizer=nltk.word_tokenize, max_features = 3000) # use top 3000 words only. 78.5% acc.
movie_counts = movie_vec.fit_transform(movie_train.data)

# min_df=2 means that the word is ignored unless shows up in at least 2 documents!

# Based on the previously written stats, we want to use all of the words because the accuracy is higher
# but 82.5% isn't very good still right?

# n-grams would be one method to improve the accuracy

In [25]:
dir(movie_vec)

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_char_ngrams', '_char_wb_ngrams', '_check_vocabulary', '_count_vocab', '_get_param_names', '_limit_features', '_sort_features', '_validate_vocabulary', '_white_spaces', '_word_ngrams', 'analyzer', 'binary', 'build_analyzer', 'build_preprocessor', 'build_tokenizer', 'decode', 'decode_error', 'dtype', 'encoding', 'fit', 'fit_transform', 'fixed_vocabulary_', 'get_feature_names', 'get_params', 'get_stop_words', 'input', 'inverse_transform', 'lowercase', 'max_df', 'max_features', 'min_df', 'ngram_range', 'preprocessor', 'set_params', 'stop_words', 'stop_words_', 'strip_accents', 'token_pattern', 'tokenizer', 'transform'

In [26]:
movie_vec.get_stop_words

<bound method VectorizerMixin.get_stop_words of CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=2,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=<function word_tokenize at 0x00000154EB9706A8>,
        vocabulary=None)>

In [27]:
# .vocabulary_.get() returns an index
movie_vec.vocabulary_.get('screen') #19637
movie_vec.vocabulary_.get('the') #22570
movie_vec.vocabulary_.get('schwarzenegger') #19574

19637

22570

19574

In [28]:
# .shape gives dimensions
movie_counts.shape
# the dimensions are very large: 2000x25313
    # 1st dimension is number of docs, 2nd dimension is unique words

(2000, 25313)

In [29]:
# Convert raw frequency counts into TF-IDF values
tfidf_transformer = TfidfTransformer()
movie_tfidf = tfidf_transformer.fit_transform(movie_counts)
    # these show how statistically siginifant the word is in the corpus
type(movie_tfidf)

<class 'scipy.sparse.csr.csr_matrix'>

In [30]:
# didn't change dimensions, but now tf-idf values instead of raw freq counts
movie_tfidf.shape

(2000, 25313)

## Sklearn's Naive Bayes

In [31]:
# Building a classifer using Multinominal Naive Bayes
from sklearn.naive_bayes import MultinomialNB

# multinomial is the kind of distribution you have with "discrete" values (like tossing a dice)
    # we use this because we have a lot of distinct features (words that appear in 2+ docs): 25313 features (words)
# gausian is another option <-- more of a continium

In [32]:
# Split data into training and test sets
# from sklearn.cross_validation import train_test_split    # what is the difference between this line and the following line?
from sklearn.model_selection import train_test_split
docs_train, docs_test, y_train, y_test = train_test_split(
    movie_tfidf, movie_train.target, test_size = 0.20, random_state = 12)

In [33]:
type(docs_train)
#help(docs_train)
docs_train.data[:2]  # I don't really understand what this means
y_train.data[:2]     # now even more confused since this is no giving a similar format..
type(y_train)        # why are the types different? what purpose does it serve?
#help(y_train)

<class 'scipy.sparse.csr.csr_matrix'>

array([ 0.05784419,  0.05969025])

<class 'numpy.ndarray'>

In [34]:
# Train a Multimoda Naive Bayes classifier
clf = MultinomialNB().fit(docs_train, y_train)

In [35]:
dir(clf)

['__abstractmethods__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_abc_cache', '_abc_negative_cache', '_abc_negative_cache_version', '_abc_registry', '_count', '_estimator_type', '_get_coef', '_get_intercept', '_get_param_names', '_joint_log_likelihood', '_update_class_log_prior', '_update_feature_log_prob', 'alpha', 'class_count_', 'class_log_prior_', 'class_prior', 'classes_', 'coef_', 'feature_count_', 'feature_log_prob_', 'fit', 'fit_prior', 'get_params', 'intercept_', 'partial_fit', 'predict', 'predict_log_proba', 'predict_proba', 'score', 'set_params']

In [36]:
# Predicting the test set results and finding accuracy
y_pred = clf.predict(docs_test)
sklearn.metrics.accuracy_score(y_test, y_pred)

0.82250000000000001

In [37]:
y_pred

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0,

In [39]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[176,  30],
       [ 41, 153]])

In [40]:
# dir(cm)
dir(y_test)

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift__', '__rmatmul__', '__rmod__', '__rmul__'

## Try Classifier on Fake Movie Reviews

In [41]:
# very short and fake movie reviews
reviews_new = ['This movie was excellent', 'Absolute joy ride', 
            'Steven Seagal was terrible', 'Steven Seagal shined through.', 
              'This was certainly a movie', 'Two thumbs up', 'I fell asleep halfway through', 
              "We can't wait for the sequel!!", '!', '?', 'I cannot recommend this highly enough', 
              'instant classic.', 'Steven Seagal was amazing. His performance was Oscar-worthy.']
reviews_new_counts = movie_vec.transform(reviews_new)
reviews_new_tfidf = tfidf_transformer.transform(reviews_new_counts)

In [42]:
# classifier's prediction
pred=clf.predict(reviews_new_tfidf)

In [43]:
# printing results
for review, category in zip(reviews_new,pred):
    print('%r => %s' % (review, movie_train.target_names[category]))
# predicts a lot of negative reviews...

'This movie was excellent' => pos
'Absolute joy ride' => pos
'Steven Seagal was terrible' => neg
'Steven Seagal shined through.' => neg
'This was certainly a movie' => neg
'Two thumbs up' => neg
'I fell asleep halfway through' => neg
"We can't wait for the sequel!!" => neg
'!' => neg
'?' => neg
'I cannot recommend this highly enough' => pos
'instant classic.' => pos
'Steven Seagal was amazing. His performance was Oscar-worthy.' => neg


## NLTK Naive Bayes Classifier

I find nltk's more intuitive, but I think that is just because I know nltk better than sklearn

I don't see a way to find most informative features in sklearn, which was very helpful when using nltk's, though I have a feeling that there is a way that I'm not seeing.

For naive bayes classifiers, what is in the document, or missing from it, is informative of what is a positive or negative review.